spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testme
    username: root
    password: sudnxp5698884
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8585
  error:
    whitelabel:
      enabled: false